AD_LOGIN: gsprom\phonebook_svc
AD_PASSWORD: wTH8An4qp0mZ
AD_SERVER: gsprom.local
AD_SEARCH_TREE: OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL
AD_FILTER: (&(objectClass=user)(memberOf=CN=Phonebook_Admin,OU=Phonebook,OU=ITSystems,OU=GROUPS,OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL))