AD_LOGIN: gsprom\kmo
AD_PASSWORD: Derk12200709!
AD_SERVER: gsprom.local
AD_SEARCH_TREE: OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL
AD_FILTER: (&(objectClass=user)(memberOf=CN=Phonebook_Admin,OU=Телефонный справочник,OU=Реестр ИТ Систем,OU=GROUPS,OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL))