ActiveDirectory:
  AD_LOGIN: gsprom\phonebook_svc
  AD_PASSWORD: DQq#%ew3ds!@
  AD_SERVER: gsprom.local
  AD_SEARCH_TREE: OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL
  AD_FILTER:
    admin: (&(objectClass=user)(memberOf=CN=Phonebook_Admin,OU=Phonebook,OU=ITSystems,OU=GROUPS,OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL))
    moderator: (&(objectClass=user)(memberOf=CN=Phonebook_Moderator,OU=Phonebook,OU=ITSystems,OU=GROUPS,OU=_GSPROM-CENTRAL,DC=GSPROM,DC=LOCAL))
SQL:
  DRIVER: ODBC Driver 17 for SQL Server
  Database: users_info
  PWD: 8RWgOmezBcXXbs7691YJ
  SERVER: sql121.isreg.ru
  UID: phonebook
Redis:
  host: 10.64.240.153
  port: 6379
